// Tests only: the thresholds of an analysis with default limits, for tests that
// build a whole Report by hand.
import type { Report } from "../report/report.js";

export const DEFAULT_THRESHOLDS: Report["thresholds"] = {
  maxCommitFiles: 50,
  hubMinBreadth: 10,
  hubMinRevisions: 5,
  hubTopShare: 0.05,
  minModuleCommits: 5,
  minVolatilityRatio: 2,
  minInterfaceChanges: 5,
  minFanIn: 5,
  minCliqueShare: 0.3,
  minLocalDistance: 3,
  minHiddenProbability: 0.5,
  minCopySimilarity: 0.5,
  minLeakage: 0.5,
  minImplementationCommits: 5,
  minSharedCommits: 3,
  minDegree: 0.3,
  propagationDepth: 3,
  ubiquitousShare: 0.3,
  ubiquitousMinCommits: 10,
  minWindowChanges: 10,
  minTrendWindows: 3,
  minErosionShift: 0.1,
  minErosionSigmas: 2,
  minVerdictWindows: 5,
  hotTopShare: 0.1,
  minConventionShare: 0.05,
  minEntryHeatShare: 0.02,
  maxEntryContainment: 0.75,
  minEntryChronicShare: 0.5,
  minEntryChanges: 3,
  minEntryCouplingChanges: 5,
  minEntryScore: 0.005,
  maxEntriesPerKind: 6,
  maxEntries: 10,
  maxCoupledTerritories: 24,
  minVerdictCoverage: 0.5,
  minMixedLeakShare: 0.2,
  minStrainedLeakShare: 0.5,
  maxMeanLineLength: 300,
  maxFileBytes: 1_048_576,
};

/** The design-fit lists of a report, all empty, and no territories. */
export const NO_DESIGN_FINDINGS = {
  verdict: {
    level: "unknown",
    reason: "no-territories",
    leakShare: 0,
    coverage: 0,
    judged: [],
    leaking: [],
    eroding: false,
    trend: "unknown",
  },
  changeRadius: null,
  propagationCost: null,
  series: [],
  seriesSince: null,
  erosion: null,
  fixDensity: {
    changes: 0,
    fixes: 0,
    conventional: 0,
    known: false,
    share: null,
  },
  cliquesPartial: false,
  dependencyDirection: [],
  unstableInterfaces: [],
  cliques: [],
  moduleCoupling: [],
  distantCouplings: [],
  territories: { recommended: 0, details: [], nodes: [] },
  territoryCoupling: [],
  territoryCliques: [],
  entryPoints: [],
} satisfies Partial<Report>;
